set proper ci cd

diff --git a/.github/workflows/playwright-tests.yml b/.github/workflows/playwright-tests.yml
--- a/.github/workflows/playwright-tests.yml
+++ b/.github/workflows/playwright-tests.yml
@@ -1,5 +1,4 @@
-name: Playwright Tests
-
+name: Validate Build
 on:
   push:
     branches:
@@ -34,6 +33,11 @@ jobs:
 
       - name: Run Integration Tests
         run: npm run test:integration
+
+      - name: run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.12.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
 
       - name: Build Project
         run: npm run build
